server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotels?useSSL=false
    username: root
    password: Qxj19960626
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.33.4
    port: 5672
    username: itcast
    password: 123321
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo